spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/
    username: 
    password: 
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
      use-new-id-generator-mapping: false

  jwt :
    header: Authorization
    secret: efnsoifh32y9t8y4rghefjdgivfoehfwe9t4hrefjvr9gt4guaerivjqir39tguerifvgwrdfjeowjoeoASFeo9283GRERgjhfv3i9138NDVSIREg
    token-validity-in-seconds:
  mvc:
    locale:
      timezone: Asia/Seoul
  file:
    upload:
      path:
        txt: C:/대학/졸작/test_chat/

  logging:
    level:
      org.springframework.web.socket: DEBUG
      org.springframework.messaging.simp: DEBUG
      org.springframework.web: DEBUG

server:
  port: 8001



